# -*- coding: utf-8 -*-
"""hw3_p1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1drhY2URxt9cfj4Z82qXdo6tTI5bdibqS
"""

import pandas as pd
import numpy as np
from statsmodels.tsa.seasonal import seasonal_decompose
  
from google.colab import drive
drive.mount('/content/drive/')

f_index = open('drive/MyDrive/hw3_prob1&2/index.txt')
gene = np.loadtxt('drive/MyDrive/hw3_prob1&2/gene.txt', dtype=float)
label = np.loadtxt('drive/MyDrive/hw3_prob1&2/label.txt', dtype=float)
feature_names = f_index.read().split('\n')

f_index.close()
label[label > 0] = 0
label[label < 0] = 1
gene = gene.transpose()

X, y = gene, label
#print(label)

import numpy as np
from sklearn.linear_model import LassoCV

lasso = LassoCV().fit(X, y)
importance = np.abs(lasso.coef_)

#print(importance)
#importance.sort()
#m = 20
#print(importance[-m:])

s = sorted(range(len(importance)), key=lambda k: importance[k])
m = 19
#print(s[-m:])

for i in range(1981,1999):
  print(feature_names[s[i]])

